`WORLD_BANK DATA EXPLORATION`

IMPORT LIB

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import os 
from pathlib import Path

`imf data`

In [ ]:
def read_csv(df):
        BASE_DIR = Path.cwd().resolve().parent.parent
        RAW_PATH = BASE_DIR /"macro_data_project" / "include" / "pipeline" /"data" / "raw" / "imf"
        file_path = RAW_PATH / f"{df}"
        return pd.read_csv(file_path)
    
dfi=read_csv('data_imf.csv')

`world_bank data`

In [ ]:
def read_csv(df):
        BASE_DIR = Path.cwd().resolve().parent.parent
        RAW_PATH = BASE_DIR /"macro_data_project" / "include" / "pipeline" /"data" / "raw" / "world_bank"
        file_path = RAW_PATH / f"{df}"
        return pd.read_csv(file_path)
    
dfw=read_csv('data_world_bank.csv')

In [ ]:
dfw

,Country,Year,Foreign Direct Investment,GDP Growth,GDP per Capita,Inflation Rate,Life Expectancy,Poverty Rate,Trade Volume,Unemployment Rate
0,Afghanistan,1980,9.000000e+06,NaN,NaN,NaN,39.258,NaN,NaN,15.680999
1,Afghanistan,1981,1.800000e+05,NaN,NaN,NaN,39.406,NaN,NaN,15.903758
2,Afghanistan,1982,1.000000e+05,NaN,NaN,NaN,36.058,NaN,NaN,16.107378
3,Afghanistan,1983,0.000000e+00,NaN,NaN,NaN,36.517,NaN,NaN,16.293666
4,Afghanistan,1984,0.000000e+00,NaN,NaN,NaN,31.473,NaN,NaN,16.464427
...,...,...,...,...,...,...,...,...,...,...
4319,Vietnam,2020,1.580000e+10,2.865413,3534.039535,3.220934,75.383,1.3,NaN,35.570668
4320,Vietnam,2021,1.566000e+10,2.553729,3704.193559,1.834716,74.145,NaN,NaN,36.654066
4321,Vietnam,2022,1.790000e+10,8.537500,4147.697772,3.156507,74.502,1.6,NaN,37.547852
4322,Vietnam,2023,1.850000e+10,5.065024,4323.350320,3.252893,74.588,NaN,NaN,38.129890
4323,Vietnam,2024,2.017000e+10,7.091187,4717.290287,3.621093,74.736,NaN,NaN,38.490070

In [ ]:
dfi

,Country,Year,Current Account Balance,Exchange Rate,Fiscal Balance,Government Debt,Interest Rate
0,Afghanistan,1980,-1200.00,108.00,-18.00,96.00,0.60
1,Afghanistan,1981,-1199.70,108.30,-17.70,96.30,0.90
2,Afghanistan,1982,-1199.40,108.60,-17.40,96.60,1.20
3,Afghanistan,1983,-1199.10,108.90,-17.10,96.90,1.50
4,Afghanistan,1984,-1198.80,109.20,-16.80,97.20,1.80
...,...,...,...,...,...,...,...
4315,Vietnam,2020,-1120.75,132.75,12.00,121.25,29.82
4316,Vietnam,2021,-1120.30,133.20,12.45,121.70,30.27
4317,Vietnam,2022,-1120.05,133.45,12.70,121.95,30.52
4318,Vietnam,2023,-1119.80,133.70,12.95,122.20,30.78
4319,Vietnam,2024,-1119.55,133.95,13.20,122.45,31.02

`merge`

In [ ]:
df_merged = dfw.merge(
    dfi,
    on=["Country", "Year"],
    how="inner"
)

`Exploration`

In [ ]:
df_merged.describe()

,Year,Foreign Direct Investment,GDP Growth,GDP per Capita,Inflation Rate,Life Expectancy,Poverty Rate,Trade Volume,Unemployment Rate,Current Account Balance,Exchange Rate,Fiscal Balance,Government Debt,Interest Rate
count,4320.000000,4.109000e+03,4113.000000,4124.000000,3871.000000,4275.000000,1872.000000,3.120000e+02,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000
mean,2002.000000,1.098049e+10,3.345805,14354.775252,29.087816,71.552886,7.266987,3.077649e+10,63.378249,-1110.273778,130.225701,10.728042,118.844972,28.367764
std,12.988677,4.099136e+10,5.478791,19309.753406,278.616333,8.126658,13.993156,3.801936e+10,21.215465,102.946016,17.532759,14.184231,16.947034,14.217797
min,1980.000000,-3.434028e+11,-64.047107,22.952133,-16.117326,31.473000,0.000000,2.550887e+08,10.374611,-1605.550000,84.070000,-18.000000,75.030000,0.500000
25%,1991.000000,1.510000e+08,1.438347,1801.276949,2.168416,67.787500,0.200000,6.422711e+09,51.382936,-1189.810000,118.200000,-2.192500,106.942500,15.550000
50%,2002.000000,1.322701e+09,3.542110,5817.384659,4.669820,72.980488,1.000000,1.849501e+10,67.323365,-1103.730000,129.350000,12.015000,118.110000,29.430000
75%,2013.000000,6.268781e+09,5.692571,20049.258230,10.350619,77.197280,7.500000,3.843732e+10,79.254480,-1026.975000,143.210000,22.177500,131.575000,39.725000
max,2024.000000,7.338265e+11,82.809329,137781.681659,11749.639632,84.580488,97.000000,2.378005e+11,100.000000,-890.630000,169.450000,41.920000,156.950000,60.360000

In [ ]:
df_merged.info()

NameError: name 'df_merged' is not defined